#if defined(__aarch64__) || (defined(__riscv_xlen) && __riscv_xlen == 64)
syscall_decl(close, 57, uint64_t fd)
syscall_decl(read, 63, uint64_t fd, const char *buf, size_t len)
syscall_decl(write, 64, uint64_t fd, const char *buf, size_t len)
syscall_decl(mmap, 222, void *addr, size_t length, int prot, int flags, int fd, off_t offset)
syscall_decl(rt_sigaction, 134, int signum, const struct sigaction *restrict act, struct sigaction *restrict oldact, size_t sigsetsize)
syscall_decl(rt_sigreturn, 139)
syscall_decl(nanosleep, 101, const struct timespec *req, struct timespec *rem)
syscall_decl(execve, 221, const char *pathname, char *const argv[], char *const envp[])
syscall_decl(exit, 93, uint64_t ret)
syscall_decl(kill, 129, uint64_t pid, uint64_t signal)
syscall_decl(sigaltstack, 132, const stack_t *restrict ss, stack_t *restrict old_ss)
syscall_decl(sync, 81)
syscall_decl(reboot, 142, uint64_t m1, uint64_t m2, uint64_t cmd, void* arg)
syscall_decl(restart_syscall, 128)
syscall_decl(waitid, 95, idtype_t idtype, id_t id, siginfo_t *infop, int options, /* struct rusage */void *ru)
syscall_decl(faccessat2, 439, int dirfd, const char *restrict pathname, int amode, int flags)
syscall_decl(mount, 40, const char *source, const char *target,
                 const char *filesystemtype, unsigned long mountflags,
                 const void * data)
syscall_decl(chroot, 51, const char *new_root)
syscall_decl(mkdirat, 34, int dirfd, const char *pathname, uint16_t mode)
syscall_decl(openat, 56, int dirfd, const char *pathname, int flags, uint16_t mode)
syscall_decl(getdents64, 61, int fd, void *dirp, size_t count)
syscall_decl(dup3, 24, int fd, int fd2, int flags)
syscall_decl(ioctl, 29, int fd, unsigned long request, void *arg)
#elif defined(__x86_64__)
syscall_decl(read, 0, uint64_t fd, const char *buf, size_t len)
syscall_decl(write, 1, uint64_t fd, const char *buf, size_t len)
syscall_decl(close, 3, int fd)
syscall_declx(mmap, 9, void *addr, size_t length, int prot, int flags, int fd, off_t offset)
syscall_declx(rt_sigaction, 13, int signum, const struct sigaction *restrict act, struct sigaction *restrict oldact, size_t sigsetsize)
syscall_decl(rt_sigreturn, 15)
syscall_decl(access, 21, const char *pathname, int mode)
syscall_decl(nanosleep, 35, const struct timespec *req, struct timespec *rem)
syscall_decl(execve, 59, const char *pathname, char *const argv[], char *const envp[])
syscall_decl(exit, 60, uint64_t ret)
syscall_decl(kill, 62, uint64_t pid, uint64_t signal)
syscall_decl(sigaltstack, 131, const stack_t *restrict ss, stack_t *restrict old_ss)
syscall_decl(sync, 162)
syscall_declx(reboot, 169, uint64_t m1, uint64_t m2, uint64_t cmd, void* arg)
syscall_decl(restart_syscall, 219)
syscall_declx(waitid, 247, idtype_t idtype, id_t id, siginfo_t *infop, int options, /* struct rusage */void *ru)
syscall_declx(faccessat2, 439, int dirfd, const char *restrict pathname, int amode, int flags)
syscall_declx(mount, 165, const char *source, const char *target,
                 const char *filesystemtype, unsigned long mountflags,
                 const void * data)
syscall_decl(chroot, 161, const char *new_root)
syscall_declx(mkdirat, 258, int dirfd, const char *pathname, uint16_t mode)
syscall_declx(openat, 257, int dirfd, const char *pathname, int flags, uint16_t mode)
syscall_decl(getdents64, 217, int fd, void *dirp, size_t count)
syscall_decl(dup3, 292, int fd, int fd2, int flags)
syscall_decl(ioctl, 16, int fd, unsigned long request, void *arg)
syscall_decl(mprotect, 10, void *addr, size_t len, int prot)
#else
#error not supported
#endif
