name: Build

on:
  workflow_dispatch:
    inputs:
      archs:
        description: "architectures, comma splited, empty for all, available: x86_64, aarch64"
        required: false
        type: string
        default: ""
  workflow_call:
    inputs:
      archs:
        description: "architectures, comma splited, empty for all, available: x86_64, aarch64"
        required: false
        type: string
        default: ""

jobs:
  gen-jobs:
    name: Generate jobs
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.gen-jobs.outputs.jobs }}
    permissions:
      contents: write
    steps:
      - name: Generate jobs
        id: gen-jobs
        shell: python -u {0}
        run: |
          import os, json

          arch = '${{ github.event.inputs.archs }}'
          if arch:
              archs = [x.strip() for x in arch.split(',')]
          else:
              archs = ['x86_64', 'aarch64']
          jobs = [{
              'arch': arch,
          } for arch in archs]
          f = open(os.environ.get('GITHUB_OUTPUT'), 'w')
          print(f'jobs={json.dumps(jobs)}', file=f)

  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    needs:
      - gen-jobs
    permissions:
      id-token: write
      contents: write
      attestations: write
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.gen-jobs.outputs.jobs) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore sources
        uses: actions/cache/restore@v4
        id: cache-restore
        with:
          path: |
            download
          key: ${{ runner.os }}-build-v1-${{ hashFiles('download') }}
          restore-keys: |
            ${{ runner.os }}-build-v1-

      - name: Prepare tools
        id: prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            --no-install-recommends \
            gawk curl tar xz-utils zstd \
            make gcc binutils elfutils \
            gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu \
            python3 python3-requests
      
      - name: Build
        id: build
        run: |
          ./build.py ${{ matrix.arch }}
          mv vmlinuz vmlinuz.${{ matrix.arch }}
          mv initramfs.img initramfs.img.${{ matrix.arch }}
          case ${{ matrix.arch }} in
            x86_64)
              EFI_SUFFIX=x64
              ;;
            aarch64)
              EFI_SUFFIX=aa64
              ;;
          esac

          echo f1=vmlinuz.${{ matrix.arch }} >> ${GITHUB_OUTPUT}
          echo f2=initramfs.img.${{ matrix.arch }} >> ${GITHUB_OUTPUT}
          echo f3=myrescue${EFI_SUFFIX}.efi >> ${GITHUB_OUTPUT}
      
      - name: Cache sources
        uses: actions/cache/save@v4
        id: cache-save
        with:
          path: |
            download
          key: ${{ runner.os }}-build-v1-${{ hashFiles('download') }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: |
            ${{ steps.build.outputs.f1 }}
            ${{ steps.build.outputs.f2 }}
            ${{ steps.build.outputs.f3 }}

      - name: Attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            ${{ steps.build.outputs.f1 }}
            ${{ steps.build.outputs.f2 }}
            ${{ steps.build.outputs.f3 }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
    steps:
      - name: Generate Release Name
        id: release-name
        run: |
          echo tag=$(date +"%Y%m%d%H%M%S") > ${GITHUB_OUTPUT}
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: automated release
          name: ${{ steps.release-name.outputs.tag }}
          tag_name: ${{ steps.release-name.outputs.tag }}
          files: |
            *
